<tr class="gray">
    <td>
        <a href="<?php echo $this->url('Tasks\add-task'); ?>" class="btn btn-success">
            <i class="icon-plus-sign icon-white"></i>
            Add
        </a>
    </td>
    <td colspan="3">
        <?php //echo (new \ReflectionClass($this->paginator))->getName();?>
        <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination-control.phtml'); ?>
        <?php //$this->paginator->getIterator()->rewind();?>
        <?php //die('zlo');?>
    </td>
</tr>