<?php if (count($this->resultSet) > 0) { ?>
    <table class="table table-striped table-bordered table-condensed">
        <thead>
            <tr>
                <th>del</th>
                <th>edit</th>
                <th>id</th>
                <th>task</th>
                <th>creation time</th>
            </tr>
        </thead>
        <tbody>
            <?php echo $this->partialLoop('tasks/index/task-row.phtml', $this->resultSet); ?>
        </tbody>
    </table>
<?php } ?>