<table class="tasks table table-bordered table-condensed">
    <thead>
        <tr class="gray">
            <th>done</th>
            <th>edit</th>
            <th>task</th>
            <th>tags</th>
        </tr>
    </thead>
    <tbody>
        <?php echo $this->render('tasks/index/control-row.phtml');?>
        <?php if (count($this->resultSet) > 0) { ?>
            <?php echo $this->partialLoop('tasks/index/task-row.phtml', $this->resultSet); ?>
        <?php } ?>
        <?php echo $this->render('tasks/index/control-row.phtml');?>
    </tbody>
</table>
