<tr>
    <td>
        <span class="badge badge-important">
            x
        </span>
    </td>
    <td>
        edit
    </td>
    <td>
        <span class="badge badge-success">
            <?php echo $this->id;?>
        </span>
        <span class="badge badge-important">
            <?php echo $this->id;?>
        </span>
        <span class="badge badge-info">
            <?php echo $this->id;?>
        </span>
        <span class="badge badge-inverse">
            <?php echo $this->id;?>
        </span>
        <span class="badge badge-warning">
            <?php echo $this->id;?>
        </span>
    </td>
    <td>
        <?php echo $this->txt;?>
    </td>
    <td>
        <?php echo $this->creation_time;?>
    </td>
</tr>