<tr>
    <td>
        <a href="<?php echo $this->url('Tasks\done-task', array('id' => $this->id));?>" class="btn btn-small btn-success">
            <i class="icon-ok icon-white"></i>
            Done
        </a>
    </td>
    <td>
        <a href="<?php echo $this->url('Tasks\edit-task', array('id' => $this->id));?>" class="btn btn-small btn-info">
            <i class=" icon-pencil icon-white"></i> Edit
        </a>
    </td>
    <td>
        <?php echo $this->txt;?>
    </td>
    <td>
        <?php echo $this->tags;?>
    </td>
</tr>