<tr>
    <td>
        <a href="<?php echo $this->url('Tasks\done-task', array('id' => $this->id));?>" class="btn btn-success">
            <i class="icon-ok icon-white"></i>
            Done
        </a>
    </td>
    <td>
        <a href="<?php echo $this->url('Tasks\edit-task', array('id' => $this->id));?>" class="btn btn-small btn-info">
            <i class=" icon-pencil icon-white"></i> Edit
        </a>
    </td>
    <td>
        <span class="badge badge-success">
            <?php echo $this->id;?>
        </span>
        <span class="badge badge-important">
            <?php echo $this->id;?>
        </span>
        <span class="badge badge-info">
            <?php echo $this->id;?>
        </span>
        <span class="badge badge-inverse">
            <?php echo $this->id;?>
        </span>
        <span class="badge badge-warning">
            <?php echo $this->id;?>
        </span>
    </td>
    <td>
        <?php echo $this->txt;?>
    </td>
    <td>
        <?php echo $this->creation_time;?>
    </td>
</tr>