<?php if(count($this->pages) > 0) {?>
    <ul class="breadcrumb">
        <?php foreach($this->pages as $key => $page) {?>
            <?php if($key < (count($this->pages)-1)) {?>
                <li>
                    <a href="<?php echo $page->getHref();?>">
                        <?php echo $page->getLabel();?>
                    </a>
                    <?php echo $this->navigation()->breadcrumbs()->getSeparator();?>
                </li>
            <?php } else {?>
                <!--last-page---------------------------------------------->
                <?php if(true == $this->navigation()->breadcrumbs()->getLinkLast()) {?>
                    <li class="active last-crumb">
                        <a href="<?php echo $page->getHref();?>">
                            <?php echo $page->getLabel();?>
                        </a>
                    </li>
                <?php } else {?>
                    <li class="active last-crumb">
                        <span>
                            <?php echo $page->getLabel();?>
                        </span>
                    </li>
                <?php }?>
            <?php }?>
        <?php }?>
    </ul>
<?php }?>
