<?php
$this->form->setAttribute('action', $this->url('Tasks\edit-task', array(
    'id' => $this->form->get('task')->get('id')->getValue(),
)));
$this->form->setAttribute('method', 'POST');
$this->form->setAttribute('class', 'form-horizontal');
$this->form->get('submit')->setAttribute('value', 'Редактировать!');
?>
<?php $this->form->prepare();?>

<script>
    $(document).ready(function() {
        console.log($('.tag-html'));
    });
    function add_category() {
        var currentCount = $('form > fieldset > fieldset').length;
        var template = $('form > fieldset > span').attr('data-template');
        template = template.replace(/__index__/g, currentCount);

        $('form > fieldset').append(template);

        return false;
    }
</script>

<?php echo $this->form()->openTag($this->form);?>
<div class="control-group">
    <label class="control-label">Теги</label>
    <div class="controls">
        <?php $tags = $this->form->get('task')->get('tags');?>
        <?php if(count($tags) > 0) {?>
            <?php foreach($tags as $tag) {?>
                <?php echo $this->formRow($tag);?>
            <?php }?>
        <?php }?>
        <a class="btn btn-success" onclick="return add_category()">
            <i class="icon-plus-sign icon-white"></i> Add tag
        </a>
        <?php ob_start();?>
            <input type='hidden' name='task[tags][__index__][id]' value=''><select name='task[tags][__index__][tag]'><option value='1'>hello</option>
            <option value='2'>world</option>
            <option value='3'>hi</option></select>
        <?php $tagHtml = ob_get_contents();ob_end_clean();?>
        <span class="tag-html" data-template="<?php echo $tagHtml;?>"></span>
    </div>
</div>
<div class="control-group">
    <label class="control-label">Приоритет</label>
    <div class="controls"><?php echo $this->formRow($this->form->get('task')->get('priority'));?></div>
</div>
<div class="control-group">
    <label class="control-label">Текст</label>
    <div class="controls"><?php echo $this->formRow($this->form->get('task')->get('txt'));?></div>
</div>
<div class="control-group">
    <div class="controls"><?php echo $this->formElement($this->form->get('submit')->setAttribute('class', 'btn btn-success'));?></div>
</div>
<?php echo $this->formHidden($this->form->get('csrf'));?>
<?php echo $this->formRow($this->form->get('task')->get('id'));?>
<?php echo $this->form()->closeTag($this->form);?>
