<?php
$this->form->setAttribute('action', $this->url('Tasks\edit-task', array(
    'id' => $this->form->get('task')->get('id')->getValue(),
)));
$this->form->setAttribute('method', 'POST');
$this->form->setAttribute('class', 'well');
$this->form->get('submit')->setAttribute('value', 'Редактировать!');
?>
<?php $this->form->prepare();?>

<?php echo $this->form()->openTag($this->form);?>
<?php echo $this->formRow($this->form->get('task')->get('id'));?>
<?php echo $this->formRow($this->form->get('task')->get('txt'));?>
<?php echo $this->formHidden($this->form->get('csrf'));?>
<?php echo $this->formElement($this->form->get('submit'));?>
<?php echo $this->form()->closeTag($this->form);?>