<?php
$class = "";

// true == $page->isActive(true) вместо true == $this->active, потому, что так
// этот элемент active, если любой из его чайлдов active
$page = new Zend\Navigation\Page\Mvc($this->vars());
if(true == $page->isActive(true)) {
    $class .= " active ";
}
if(count($this->pages) > 0) {
    $class .= " dropdown-submenu ";
}
?>
<li class="<?php echo $class;?>">
    <a href="<?php echo $this->url($this->route);?>">
        <?php echo $this->label;?>
        <?php //\Zend\Debug\Debug::dump($this->active);exit();?>
    </a>
    <?php if(count($this->pages) > 0) {?>
        <ul class="dropdown-menu">
            <?php echo $this->partialLoop('helper/header-nav/subitem-row', $this->pages);?>
        </ul>
    <?php }?>
</li>