<?php echo $this->doctype(); ?>

<html>
    <head>
        <?php echo $this->head();?>
    </head>
    <body>
        <header class="row-fluid">
            <?php echo $this->header(); ?>
        </header>
        <section class="row-fluid wrapper">
            <section class="span8 content">
                <?php echo $this->content; ?>
            </section>
            <aside class="span4 side-right hidden-phone hidden-tablet">
                <?php echo $this->sideRight(); ?>
            </aside>
        </section>
        <footer class="row-fluid">
            <?php echo $this->footer(); ?>
        </footer>
    </body>
</html>
