<?php
$this->form->setAttribute('action', $this->url('Tasks\edit-task', array(
    'id' => $this->form->get('task')->get('id')->getValue(),
)));
$this->form->setAttribute('method', 'POST');
$this->form->setAttribute('class', 'form-horizontal');
$this->form->get('submit')->setAttribute('value', 'Редактировать!');
?>
<?php $this->form->prepare();?>

<?php echo $this->form()->openTag($this->form);?>
<div class="control-group">
    <label class="control-label">Теги</label>
    <div class="controls"><?php echo $this->formRow($this->form->get('task')->get('tags'));?></div>
</div>
<div class="control-group">
    <label class="control-label">Приоритет</label>
    <div class="controls"><?php echo $this->formRow($this->form->get('task')->get('priority'));?></div>
</div>
<div class="control-group">
    <label class="control-label">Текст</label>
    <div class="controls"><?php echo $this->formRow($this->form->get('task')->get('txt'));?></div>
</div>
<div class="control-group">
    <div class="controls"><?php echo $this->formElement($this->form->get('submit')->setAttribute('class', 'btn btn-info'));?></div>
</div>
<?php echo $this->formHidden($this->form->get('csrf'));?>
<?php echo $this->formRow($this->form->get('task')->get('id'));?>
<?php echo $this->form()->closeTag($this->form);?>
