<?php
$this->form->setAttribute('method', 'POST');
$this->form->setAttribute('class', 'form-horizontal');
?>
<?php $this->form->prepare();?>

<?php echo $this->formTwb()->openTag($this->form);?>
<div class="control-group">
    <label class="control-label">
        Текст
        <span class="required">*</span>
    </label>
    <div class="controls"><?php echo $this->formTextareaTwb($this->form->get('note')->get('txt'));?></div>
</div>
<div class="control-group">
    <div class="controls"><?php echo $this->formElementTwb($this->form->get('submit')->setAttribute('class', 'btn btn-info'));?></div>
</div>
<?php echo $this->formHiddenTwb($this->form->get('csrf'));?>
<?php echo $this->formRowTwb($this->form->get('note')->get('id'));?>
<?php echo $this->formTwb()->closeTag($this->form);?>
