<?php
$title = 'My tasks';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>
    <a href="<?php echo $this->url('tasks', array('action'=>'add'));?>">
        Add new tasks
    </a>
</p>

<table class="table">
    <tr>
        <th>Title</th>
        <th>Artist</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach($tasks as $task) : ?>
        <tr>
            <td>
                <?php echo $this->escapeHtml($task->title);?>
            </td>
            <td>
                <?php echo $this->escapeHtml($task->artist);?>
            </td>
            <td>
                <a href="<?php echo $this->url('tasks', array('action'=>'edit', 'id' => $task->id));?>">
                    Edit
                </a>
                <a href="<?php echo $this->url('tasks', array('action'=>'delete', 'id' => $task->id));?>">
                    Delete
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>