<?php $this->headTitle($this->title);?>
<h1><?php echo $this->escapeHtml($this->title); ?></h1>

<?php
$colorsArr = array(
    'red',
    'blue',
);
?>
<?php
class Hello_World
{
    public $x = 10;
    public $y = 20;
    
    public function toArrayX()
    {
        return array(
            'y' => '25',
        );
    }
}
?>
<?php $this->partial()->setObjectKey('ololo');?>

<?php //echo (new ReflectionObject($this->headTitle()))->getName();?>
<?php $this->headTitle('Hello');?>
<?php $this->headTitle('Kui');?>
<?php $this->headTitle('User');?>
<?php $this->headTitle('Admin');?>
<?php $this->headTitle('Алиса');?>

<?php
//$viewRenderer = new Zend\View\Renderer\PhpRenderer();
//$broker = $viewRenderer->getBroker();
//$loader = $broker->getClassLoader();
//
//// Register singly:
//$loader->registerPlugin('lowercase', 'My\Helper\LowerCase');
//
//// Register several:
//$loader->registerPlugins(array(
//    'lowercase' => 'My\Helper\LowerCase',
//    'uppercase' => 'My\Helper\UpperCase',
//));
?>
<?php //echo $this->specialPurpose();?>

<?php //echo $this->baseUrl;?>
<?php //echo $this->partial('partials/hello.phtml', 'application', new Hello_World);?>
<?php //echo $this->partial('album/album/add.phtml', $colorsArr);?>

<?php
//$broker = $this->getBroker();
//echo (new ReflectionObject($broker))->getName();
?>