<div class="text">
    Hello, world!
</div>
<ul class="nav nav-list">
    ...
    <li>
        <a href="#">
            <i class="icon-book"></i>
            Библиотека
            <i class="icon-white icon-home"></i>
        </a>
    </li>
    ...
</ul>


<div style="margin-bottom: 18px;" class="tabbable"><!-- Only required for left/right tabs -->
    <ul class="nav nav-tabs">
        <li class="active"><a data-toggle="tab" href="#tab1">Вкладка 1</a></li>
        <li><a data-toggle="tab" href="#tab2">Вкладка 2</a></li>
        <li><a data-toggle="tab" href="#tab3">Вкладка 3</a></li>
    </ul>
    <div style="padding-bottom: 9px; border-bottom: 1px solid #ddd;" class="tab-content">
        <div id="tab1" class="tab-pane active">
            <p>Я 1-я секция.</p>
        </div>
        <div id="tab2" class="tab-pane">
            <p>Привет, я 2-я секция.</p>
        </div>
        <div id="tab3" class="tab-pane">
            <p>Как дела? Это 3-я секция.</p>
        </div>
    </div>
</div>

<div class="navbar">
    <div class="navbar-inner">
        <div class="container">
            ...
            <ul class="nav">
                <li class="active">
                    <a href="#">Главная</a>
                </li>
                <li><a href="#">Ссылка</a></li>
                <li><a href="#">Ссылка</a></li>
                <li><a href="#">Ссылка</a></li>
                <li class="divider-vertical"></li>
                <li class="divider"></li>
                <li class="divider"></li>
                <li class="divider"></li>
                <li class="divider"></li>
                <li class="pull-right"><a href="#">Ссылка</a></li>
                <li class="dropdown">
                    <a href="#"
                       class="dropdown-toggle"
                       data-toggle="dropdown">
                        Account
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="active">
                            <a href="#">Главная</a>
                        </li>
                        <li><a href="#">Ссылка</a></li>
                        <li><a href="#">Ссылка</a></li>
                        <li><a href="#">Ссылка</a></li>
                        <li class="divider-vertical"></li>
                        <li class="divider"></li>
                        <li class="divider"></li>
                        <li class="divider"></li>
                        <li class="divider"></li>
                        <li class="pull-right"><a href="#">Ссылка</a></li>
                        <li class="dropdown">
                            <a href="#"
                               class="dropdown-toggle"
                               data-toggle="dropdown">
                                Account
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                ...
                            </ul>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
        <a class="brand" href="#">
            Имя проекта
        </a>
        <form class="navbar-form pull-left">
            <input type="text" class="span2">
        </form>
        <form class="navbar-search pull-right">
            <input type="text" class="search-query" placeholder="Поиск">
        </form>
    </div>
    <ul class="nav">

    </ul>
</div>
<ul class="breadcrumb">
    <li>
        <a href="#">Главная</a> <span class="divider">/</span>
    </li>
    <li>
        <a href="#">Библиотека</a> <span class="divider">/</span>
    </li>
    <li class="active">Информация</li>
</ul>
<div class="pagination">
    <ul>
        <li><a href="#">Пред</a></li>
        <li class="active">
            <a href="#">1</a>
        </li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">След</a></li>
    </ul>
</div>
<div class="pagination pagination-centered">
    <ul>
        <li><a href="#">Пред</a></li>
        <li class="active">
            <a href="#">1</a>
        </li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">След</a></li>
    </ul>
</div>

<ul class="pager">
    <li>
        <a href="#">Назад</a>
    </li>
    <li>
        <a href="#">Вперед</a>
    </li>
</ul>

<div class="pagination pagination-centered">
    <ul class="pager">
        <li class="previous">
            <a href="#">&larr; Назад</a>
        </li>
        <li><a href="#">Пред</a></li>
        <li class="active">
            <a href="#">1</a>
        </li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">След</a></li>
        <li class="next">
            <a href="#">Вперед &rarr;</a>
        </li>
    </ul>
</div>
<div class="hero-unit">
    <h1>Заголовок</h1>
    <p>Ключевой текст</p>
    <p>
        <a class="btn btn-primary btn-large">
            Узнать больше
        </a>
    </p>
</div>
<div class="page-header">
    <h1>Пример заголовка страницы <small>Дополнительный текст здесь</small></h1>
</div>
<ul class="thumbnails">
    <li class="span2">
        <a href="#" class="thumbnail">
            <img src="http://placehold.it/260x180" alt="">
        </a>
    </li>
    <li class="span2">
        <a href="#" class="thumbnail">
            <img src="http://placehold.it/260x180" alt="">
        </a>
    </li>
    <li class="span2">
        <a href="#" class="thumbnail">
            <img src="http://placehold.it/260x180" alt="">
        </a>
    </li>
    <li class="span2">
        <a href="#" class="thumbnail">
            <img src="http://placehold.it/260x180" alt="">
        </a>
    </li>
    <li class="span2">
        <a href="#" class="thumbnail">
            <img src="http://placehold.it/260x180" alt="">
        </a>
    </li>
    <li class="span1 offset1">
        <a href="#" class="thumbnail">
            <img src="http://placehold.it/260x180" alt="">
        </a>
    </li>
</ul>
<div class="span12">
    <div class="span8">
        <ul class="thumbnails">
            <li class="span8">
                <a class="thumbnail" href="#">
                    <img alt="" src="http://placehold.it/360x268">
                </a>
            </li>
            <li class="span2">
                <a class="thumbnail" href="#">
                    <img alt="" src="http://placehold.it/160x120">
                </a>
            </li>
            <li class="span2">
                <a class="thumbnail" href="#">
                    <img alt="" src="http://placehold.it/160x120">
                </a>
            </li>
            <li class="span2">
                <a class="thumbnail" href="#">
                    <img alt="" src="http://placehold.it/160x120">
                </a>
            </li>
            <li class="span2">
                <a class="thumbnail" href="#">
                    <img alt="" src="http://placehold.it/160x120">
                </a>
            </li>
            <li class="span2">
                <a class="thumbnail" href="#">
                    <img alt="" src="http://placehold.it/160x120">
                </a>
            </li>
        </ul>
    </div>
    <div class="span4">

    </div>
</div>
<div class="alert span12">
    <button class="close" data-dismiss="alert">×</button>
    <strong>Предупреждение!</strong> Nulla vitae elit libero, a pharetra augue.
</div>
<div class="alert alert-error">
    ...
</div>
<div class="alert alert-success">
    ...
</div>
<div class="alert alert-info">
    ...
</div>

<div class="progress">
    <div class="bar"
         style="width: 60%;"></div>
</div>
<div class="progress progress-striped">
    <div class="bar"
         style="width: 20%;"></div>
</div>
<div class="progress progress-striped
     active">
    <div class="bar"
         style="width: 40%;"></div>
</div>
<div class="well">
    Hello, world!
</div>

<button class="close">&times;</button>
<a class="close" href="#">&times;</a>