<?php
// headTitle
$this->headTitle('Tasker');
$this->headTitle()->setSeparator(' - ');
$this->headTitle()->setAutoEscape(false);

// headMeta
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0');

// headLink
$this->headLink(array(
    'rel' => 'shortcut icon',
    'type' => 'image/vnd.microsoft.icon',
    'href' => $this->basePath() . '/img/favicon.ico',
));

//$this->headLink()->prependStylesheet(array(
//    'rel' => 'stylesheet/less',
//    'type' => 'text/css',
//    'href' => $this->basePath() . '/css/index.less',
//));

$this->headLink()->appendStylesheet($this->basePath() . '/css/dlu-tw-bootstrap.css');

$this->headLink()->prependStylesheet($this->basePath() . '/css/adaptive/phone.css');
$this->headLink()->prependStylesheet($this->basePath() . '/css/adaptive/tablet.css');
$this->headLink()->prependStylesheet($this->basePath() . '/css/adaptive/desktop.css');

$this->headLink()->prependStylesheet($this->basePath() . '/css/index.css');
$this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css');
$this->headLink()->prependStylesheet($this->basePath() . '/css/bootstrap.min.css');

// headScript
//$this->headScript()->prependFile($this->basePath() . '/js/less.js');
//$this->inlineScript()->appendFile('');
$this->headScript()->appendFile($this->basePath() . '/js/jquery-1.8.0.min.js');
$this->headScript()->appendFile($this->basePath() . '/js/bootstrap.min.js');
$this->headScript()->appendFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',));

?>

<meta charset="utf-8">

<?php echo $this->headTitle();?>
<?php echo $this->headMeta();?>
<?php echo $this->headLink();?>
<?php echo $this->headScript();?>

<?php
//Для корректного отображения и работы динамических медиа-запросов,
//необходимо включить viewport meta - тег.
//<meta name="viewport" content="width=device-width, initial-scale=1.0">
?>
<meta name="viewport" content="width=480px, initial-scale=1.0">

<script>
//    $(document).ready(function() {
//        console.log('ok');
//        less.watch();
//    });
</script>
