<div class="text">
    Hi, this is right column
</div>
<div class="btn-toolbar">
    <div class="btn-group">
        <button class="btn">Лево</button>
        <button class="btn">Середина</button>
    </div>
    <button class="btn">Право</button>
</div>
<div class="btn-toolbar">
    <div class="btn-group">
        <button class="btn-mini">Лево</button>
        <button class="btn-large">Середина</button>
        <button class="btn-small">Середина</button>
        <button>Середина</button>
    </div>
    <button class="btn">Право</button>
</div>
<div class="btn-group">
    <button class="btn dropdown-toggle btn-warning" data-toggle="dropdown">Действие <span class="caret"></span></button>
    <button class="btn dropdown-toggle btn-warning" data-toggle="dropdown">Действие <span class="caret"></span></button>
    <ul class="dropdown-menu">
        <li><a href="#">Действие</a></li>
        <li><a href="#">Другое действие</a></li>
        <li><a href="#">Еще и еще</a></li>
        <li class="divider"></li>
        <li><a href="#">Отделенный пункт</a></li>
    </ul>
</div>
<div class="btn-group">
    <button class="btn btn-inverse">Действие</button>
    <button class="btn dropdown-toggle btn-success" data-toggle="dropdown"><span class="caret"></span></button>
    <ul class="dropdown-menu">
        <li><a href="#">Действие</a></li>
        <li><a href="#">Другое действие</a></li>
        <li><a href="#">Еще и еще</a></li>
        <li class="divider"></li>
        <li><a href="#">Отделенный пункт</a></li>
    </ul>
</div>
<div class="btn-group dropup">
    <button class="btn btn-inverse">Действие</button>
    <button class="btn dropdown-toggle dropdown-toggle btn-success" data-toggle="dropdown"><span class="caret"></span></button>
    <ul class="dropdown-menu">
        <li><a href="#">Действие</a></li>
        <li><a href="#">Другое действие</a></li>
        <li><a href="#">Еще и еще</a></li>
        <li class="divider"></li>
        <li><a href="#">Отделенный пункт</a></li>
    </ul>
</div>
<ul class="nav nav-tabs">
    <li class="active"><a href="#">Главная</a></li>
    <li><a href="#">Профиль</a></li>
    <li><a href="#">Сообщения</a></li>
</ul>
<ul class="nav nav-pills">
    <li class="active"><a href="#">Главная</a></li>
    <li><a href="#">Профиль</a></li>
    <li><a href="#">Сообщения</a></li>
</ul>
<ul class="nav nav-tabs">
    <li class="active"><a href="#">Главная</a></li>
    <li><a href="#">Профиль</a></li>
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Выпадающий список <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li><a href="#">Действие</a></li>
            <li><a href="#">Другое действие</a></li>
            <li><a href="#">Еще и еще</a></li>
            <li class="divider"></li>
            <li><a href="#">Отделенный пункт</a></li>
        </ul>
    </li>
</ul>
<ul class="nav nav-list">
    ...
    <li class="divider"></li>
    ...
</ul>
<ul class="nav nav-list">
    <li class="nav-header">
        Заголовок
    </li>
    <li class="active">
        <a href="#">Главная</a>
    </li>
    <li>
        <a href="#">Библиотека</a>
    </li>
    <li class="divider"></li>
    <li>
        <a href="#"></a>
    </li>
</ul>